###########################################################
##  MSEEI 2023-2024
##  Basys3 General Purpose I/O
###########################################################

## Irene Mateos Dom?nguez
## DNI: 48259794K

## 	LEDs
set_property PACKAGE_PIN U16 [get_ports {LED[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[0]}]
set_property PACKAGE_PIN E19 [get_ports {LED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
set_property PACKAGE_PIN U19 [get_ports {LED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]
set_property PACKAGE_PIN V19 [get_ports {LED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[3]}]
set_property PACKAGE_PIN W18 [get_ports {LED[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[4]}]
set_property PACKAGE_PIN U15 [get_ports {LED[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[5]}]
set_property PACKAGE_PIN U14 [get_ports {LED[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[6]}]
set_property PACKAGE_PIN V14 [get_ports {LED[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[7]}]
set_property PACKAGE_PIN V13 [get_ports {LED[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[8]}]
set_property PACKAGE_PIN V3 [get_ports {LED[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[9]}]
set_property PACKAGE_PIN W3 [get_ports {LED[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[10]}]
set_property PACKAGE_PIN U3 [get_ports {LED[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[11]}]
#set_property PACKAGE_PIN P3 [get_ports {LED[12]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {LED[12]}]
#set_property PACKAGE_PIN N3 [get_ports {LED[13]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {LED[13]}]
#set_property PACKAGE_PIN P1 [get_ports {LED[14]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {LED[14]}]
#set_property PACKAGE_PIN L1 [get_ports {LED[15]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {LED[15]}]

# LED[12]
set_property PACKAGE_PIN P3 [get_ports {DEBUG[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DEBUG[0]}]
# LED[13]
set_property PACKAGE_PIN N3 [get_ports {DEBUG[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DEBUG[1]}]
# LED[14]
set_property PACKAGE_PIN P1 [get_ports {DEBUG[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DEBUG[2]}]
# LED[15]
set_property PACKAGE_PIN L1 [get_ports {DEBUG[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DEBUG[3]}]


##7	segment display
set_property PACKAGE_PIN W7 [get_ports {CAT[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CAT[0]}]
set_property PACKAGE_PIN W6 [get_ports {CAT[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CAT[1]}]
set_property PACKAGE_PIN U8 [get_ports {CAT[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CAT[2]}]
set_property PACKAGE_PIN V8 [get_ports {CAT[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CAT[3]}]
set_property PACKAGE_PIN U5 [get_ports {CAT[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CAT[4]}]
set_property PACKAGE_PIN V5 [get_ports {CAT[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CAT[5]}]
set_property PACKAGE_PIN U7 [get_ports {CAT[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CAT[6]}]
set_property PACKAGE_PIN V7 [get_ports {CAT[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CAT[7]}]

set_property PACKAGE_PIN U2 [get_ports {AN[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[0]}]
set_property PACKAGE_PIN U4 [get_ports {AN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[1]}]
set_property PACKAGE_PIN V4 [get_ports {AN[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[2]}]
set_property PACKAGE_PIN W4 [get_ports {AN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[3]}]


###########################################################
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
###########################################################

# Pulsadores y switches
# XRES = BTNC; XBOOTSEL = BTNL; BTN[0]=BTNU; BTN[1]=BTNR; BTN[2]=BTND;
set_property PACKAGE_PIN U18 [get_ports XRES]
set_property IOSTANDARD LVCMOS33 [get_ports XRES]
set_property PACKAGE_PIN W19 [get_ports XBOOTSEL]
set_property IOSTANDARD LVCMOS33 [get_ports XBOOTSEL]
set_property PACKAGE_PIN T18 [get_ports XBTN[0]]
set_property IOSTANDARD LVCMOS33 [get_ports XBTN[0]]
set_property PACKAGE_PIN T17 [get_ports XBTN[1]]
set_property IOSTANDARD LVCMOS33 [get_ports XBTN[1]]
set_property PACKAGE_PIN U17 [get_ports XBTN[2]]
set_property IOSTANDARD LVCMOS33 [get_ports XBTN[2]]
#Switches
set_property PACKAGE_PIN V17 [get_ports {XSW[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {XSW[0]}]
set_property PACKAGE_PIN V16 [get_ports {XSW[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {XSW[1]}]
set_property PACKAGE_PIN W16 [get_ports {XSW[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {XSW[2]}]
set_property PACKAGE_PIN W17 [get_ports {XSW[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {XSW[3]}]
set_property PACKAGE_PIN W15 [get_ports {XSW[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {XSW[4]}]
set_property PACKAGE_PIN V15 [get_ports {XSW[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {XSW[5]}]
set_property PACKAGE_PIN W14 [get_ports {XSW[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {XSW[6]}]
set_property PACKAGE_PIN W13 [get_ports {XSW[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {XSW[7]}]
set_property PACKAGE_PIN V2 [get_ports {XSW[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {XSW[8]}]
set_property PACKAGE_PIN T3 [get_ports {XSW[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {XSW[9]}]
set_property PACKAGE_PIN T2 [get_ports {XSW[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {XSW[10]}]
set_property PACKAGE_PIN R3 [get_ports {XSW[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {XSW[11]}]
set_property PACKAGE_PIN W2 [get_ports {XSW[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {XSW[12]}]
set_property PACKAGE_PIN U1 [get_ports {XSW[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {XSW[13]}]
set_property PACKAGE_PIN T1 [get_ports {XSW[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {XSW[14]}]
set_property PACKAGE_PIN R2 [get_ports {XSW[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {XSW[15]}]

# Configuración del reloj que viene en la placa Basys3 (100MHz)
set_property IOSTANDARD LVCMOS33 [get_ports XCLK]
set_property PACKAGE_PIN W5 [get_ports XCLK]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports XCLK]

# UART
set_property PACKAGE_PIN B18 [get_ports UART_RXD]
set_property PACKAGE_PIN A18 [get_ports UART_TXD]
set_property IOSTANDARD LVCMOS33 [get_ports UART_RXD]
set_property IOSTANDARD LVCMOS33 [get_ports UART_TXD]

#I2C
set_property PACKAGE_PIN A17 [get_ports I2C_SCL]
set_property PACKAGE_PIN A15 [get_ports I2C_SDA]
set_property IOSTANDARD LVCMOS33 [get_ports I2C_SCL]
set_property IOSTANDARD LVCMOS33 [get_ports I2C_SDA]
set_property DRIVE 4 [get_ports I2C_SDA]
set_property DRIVE 4 [get_ports I2C_SCL]

#SPI
set_property PACKAGE_PIN A14 [get_ports SPI_CLK]
set_property PACKAGE_PIN A16 [get_ports SPI_MISO]
set_property PACKAGE_PIN B15 [get_ports SPI_MOSI]
set_property PACKAGE_PIN B16 [get_ports SPI_CS1]
set_property PACKAGE_PIN C15 [get_ports SPI_CS2]
set_property PACKAGE_PIN C16 [get_ports SPI_CS3]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_MISO]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_MOSI]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_CS1]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_CS2]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_CS3]
set_property SLEW FAST [get_ports SPI_CLK]
set_property SLEW FAST [get_ports SPI_MOSI]
set_property OFFCHIP_TERM NONE [get_ports SPI_CLK]
set_property OFFCHIP_TERM NONE [get_ports SPI_CS1]
set_property OFFCHIP_TERM NONE [get_ports SPI_CS2]
set_property OFFCHIP_TERM NONE [get_ports SPI_CS3]
set_property OFFCHIP_TERM NONE [get_ports SPI_MOSI]

# GPIO/PWM
# GPIO on JA
set_property PACKAGE_PIN J1 [get_ports {GPIO[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO[0]}]
set_property PACKAGE_PIN L2 [get_ports {GPIO[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO[1]}]
set_property PACKAGE_PIN J2 [get_ports {GPIO[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO[2]}]
set_property PACKAGE_PIN G2 [get_ports {GPIO[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO[3]}]
set_property PACKAGE_PIN H1 [get_ports {GPIO[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO[4]}]
set_property PACKAGE_PIN K2 [get_ports {GPIO[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO[5]}]
set_property PACKAGE_PIN H2 [get_ports {GPIO[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO[6]}]
set_property PACKAGE_PIN G3 [get_ports {GPIO[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO[7]}]

# GPIO on JC
set_property PACKAGE_PIN K17 [get_ports {GPIO[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO[8]}]
set_property PACKAGE_PIN M18 [get_ports {GPIO[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO[9]}]
set_property PACKAGE_PIN N17 [get_ports {GPIO[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO[10]}]
set_property PACKAGE_PIN P18 [get_ports {GPIO[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO[11]}]
set_property PACKAGE_PIN L17 [get_ports {GPIO[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO[12]}]
set_property PACKAGE_PIN M19 [get_ports {GPIO[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO[13]}]
set_property PACKAGE_PIN P17 [get_ports {GPIO[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO[14]}]
set_property PACKAGE_PIN R18 [get_ports {GPIO[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO[15]}]
